name: pomodoro

on:
  push:
    branches:
      - master

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install --legacy-peer-deps
          npm run build
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact
  deploy:
    need: build
    permission:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    - name: Deploy
      uses: actions/deploy-pages

      runs-on: ubuntu-latest
      steps:
        - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: build